"""Initial n

Revision ID: 19b52728d205
Revises: 9f3f6eb6d5b0
Create Date: 2025-06-20 00:27:12.336487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b52728d205'
down_revision = '9f3f6eb6d5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
