"""Add file_path column to music_video table

Revision ID: 699959066bb6
Revises: c683b6f2c49d
Create Date: 2025-07-13 20:42:56.024384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699959066bb6'
down_revision = 'c683b6f2c49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
