"""Initial migration

Revision ID: 9f3f6eb6d5b0
Revises: 
Create Date: 2025-06-20 00:12:31.511649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3f6eb6d5b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('youtube_link', sa.String(length=200), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('music_video')
    # ### end Alembic commands ###
