"""Add file_path column to music_video table

Revision ID: c683b6f2c49d
Revises: 19b52728d205
Create Date: 2025-07-13 20:24:41.350406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c683b6f2c49d'
down_revision = '19b52728d205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
