"""Add file_path column to music_video table

Revision ID: dc0aa72972fa
Revises: 699959066bb6
Create Date: 2025-07-14 02:07:24.105202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0aa72972fa'
down_revision = '699959066bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
