"""Add description to MusicVideo

Revision ID: e6919541e0c6
Revises: dc0aa72972fa
Create Date: 2025-07-14 02:42:20.967284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6919541e0c6'
down_revision = 'dc0aa72972fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_video', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
